### ISSUE TITLE
WP Engine fatal error on activation

### ISSUE THREAD

**Issue by cartpauj** [afragen/wp-debugging#7]
I get this when activating the plugin on WP Engine usually. Though it has occurred on some other hosting environments like HostGator as well.

```
Fatal error: Uncaught Exception: Unable to locate placement anchor. in /home2/site/public_html/eng/wp-content/plugins/wp-debugging/vendor/wp-cli/wp-config-transformer/src/WPConfigTransformer.php:144

Stack trace:
#0 /home2/site/public_html/eng/wp-content/plugins/wp-debugging/vendor/wp-cli/wp-config-transformer/src/WPConfigTransformer.php(184): WPConfigTransformer->add('constant', 'WP_DEBUG', 'true', Array)

#1 /home2/site/public_html/eng/wp-content/plugins/wp-debugging/src/Settings.php(152): WPConfigTransformer->update('constant', 'WP_DEBUG', 'true', Array)

#2 /home2/site/public_html/eng/wp-content/plugins/wp-debugging/src/Bootstrap.php(166): Fragen\WP_Debugging\Settings->add_constants(Array)

#3 /home2/site/public_html/eng/wp-includes/class-wp-hook.php(286): Fragen\WP_Debugging\Bootstrap->activate('')

#4 /home2/site/public_html/eng/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)

#5 /home2/site/public_html/eng/wp-includes/plugin.php(465): WP_Hook->do_action(Array)

#6 /home2/site/ in /home2/site/public_html/eng/wp-content/plugins/wp-debugging/vendor/wp-cli/wp-config-transformer/src/WPConfigTransformer.php on line 144
```

**Comment by afragen** [comment]
That error is be auth our `wp-config.php` does not have the standard anchor line as follows. You will need to add it for this plugin to function. 

`/* That's all, stop editing! Happy blogging. */`

It may say Happy publishing instead of Happy blogging.
